name: Despliegue contínuo
on: [push]
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Instalar llave SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'holaholahola'
    - name: Configurar known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Clonar repositorio
      uses: actions/checkout@v3
    - name: Desplegar con rsync
      run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/backend
